### PR TITLE
fix(git): expand changed_lines to full hunk range

### LINKED ISSUE #62: affected silently misses downstream consumers when hunk start line is a non-export (imports / interfaces)
## Summary

`domino affected` silently misses downstream consumers when the first line of every diff hunk for a changed file lands on a node kind that isn't handled by `find_node_at_line`'s walk-up (e.g. imports, non-exported `interface` / `type` declarations). The change still marks the file's owning package as affected, but no reference traversal is performed, so any package that imports the changed symbol is dropped from the affected set.

This is not theoretical — it happens on any real-world PR whose shape happens to produce hunks starting on non-analyzable declarations. The change to the public surface of a workspace package is fully invisible to `affected`.

## Reproduction

Run this in an empty directory with `git`, `node`, and `npx` available. No `node_modules` or installs required:

```bash
mkdir -p packages/package-a/src packages/package-b/src

cat > rush.json <<'EOF'
{
  "rushVersion": "5.102.0",
  "pnpmVersion": "8.7.6",
  "nodeSupportedVersionRange": ">=18.0.0",
  "projects": [
    { "packageName": "package-a", "projectFolder": "packages/package-a" },
    { "packageName": "package-b", "projectFolder": "packages/package-b" }
  ]
}
EOF

cat > packages/package-a/package.json <<'EOF'
{ "name": "package-a", "version": "0.0.0", "main": "src/index.ts" }
EOF

cat > packages/package-a/src/index.ts <<'EOF'
export { foo } from './foo.js';
EOF

cat > packages/package-a/src/helper.ts <<'EOF'
export const helper = (x: number): number => x * 2;
EOF

cat > packages/package-a/src/foo.ts <<'EOF'
import { helper } from './helper.js';

export const foo = (x: number): number => helper(x) + 1;
EOF

cat > packages/package-b/package.json <<'EOF'
{ "name": "package-b", "version": "0.0.0", "main": "src/index.ts", "dependencies": { "package-a": "workspace:*" } }
EOF

cat > packages/package-b/src/index.ts <<'EOF'
import { foo } from 'package-a';

export const callFoo = (x: number): number => foo(x) + 10;
EOF

git init -q -b main
git -c user.email=r@r.com -c user.name=r add -A
git -c user.email=r@r.com -c user.name=r commit -q -m "base"

# Branch A: small in-place edit to foo's body
git checkout -q -b simple-edit
sed -i.bak 's/+ 1;/+ 2;/' packages/package-a/src/foo.ts && rm packages/package-a/src/foo.ts.bak
git -c user.email=r@r.com -c user.name=r commit -q -am "simple-edit"

# Branch B: replace the export line with an interface + new export
git checkout -q main
git checkout -q -b rewrite
cat > packages/package-a/src/foo.ts <<'EOF'
import { helper } from './helper.js';

interface FooOptions {
  offset: number;
  multiplier: number;
}

export const foo = (x: number, options: FooOptions = { offset: 1, multiplier: 3 }): number =>
  helper(x) * options.multiplier + options.offset;
EOF
git -c user.email=r@r.com -c user.name=r commit -q -am "rewrite"

# Run domino against each branch
echo "simple-edit: $(git checkout -q simple-edit && npx --yes @front-ops/domino@latest affected --base main --json 2>&1 | tail -1)"
echo "rewrite:     $(git checkout -q rewrite     && npx --yes @front-ops/domino@latest affected --base main --json 2>&1 | tail -1)"
```

## Expected vs actual

Both branches change exactly one file — `packages/package-a/src/foo.ts`, a module `package-b` imports from. Both change the behaviour of the exported `foo`. `package-b` is equally affected by both changes.

```
simple-edit: ["package-a","package-b"]   ✅
rewrite:     ["package-a"]               ❌  (package-b missing)
```

The `rewrite` branch differs from `simple-edit` only in the shape of the diff — the `interface FooOptions` block was inserted between the existing imports and the export. No other file in the repo changed.

## Root cause

With `--unified=0` (as used by `get_diff` in `src/git.rs:111`), the two diffs look like:

```
simple-edit:
@@ -3 +3 @@
-export const foo = (x: number): number => helper(x) + 1;
+export const foo = (x: number): number => helper(x) + 2;

rewrite:
@@ -3 +3,7 @@
-export const foo = (x: number): number => helper(x) + 1;
+interface FooOptions {
+  offset: number;
+  multiplier: number;
+}
+
+export const foo = (x: number, options: FooOptions = { offset: 1, multiplier: 3 }): number =>
+  helper(x) * options.multiplier + options.offset;
```

Both hunks start at new-file line 3 — `LINE_RE` in `src/git.rs:11` captures `3` for each. In `src/core.rs:146-161`, that single line number is fed to `analyzer.find_node_at_line(file_path, 3, 0)` to look up a containing exported declaration in the **new** file.

- In `simple-edit`, new-file line 3 is `export const foo = ...` — an `ExportNamedDeclaration`. The match in `src/semantic/analyzer.rs:897-916` fires, returns `"foo"`, reference traversal finds `package-b`. ✅
- In `rewrite`, new-file line 3 is `interface FooOptions {` — a `TSInterfaceDeclaration`. There is no match arm for interfaces in `analyzer.rs:897-930`, and the walk-up loop below it only recognizes `ExportNamedDeclaration` / `ExportDefaultDeclaration`. The parent of `TSInterfaceDeclaration` is the `Program` root, so walk-up terminates without a result. `find_node_at_line` returns `[]`, `symbols_by_line` is empty, and `core.rs:205-209` logs:

```
DEBUG No traceable symbols found in "packages/package-a/src/foo.ts", skipping reference traversal
```

Reference traversal is skipped entirely. `package-b` never gets looked at.

The same pattern reproduces whenever the first line of every hunk happens to land on something the walk-up doesn't recognize — imports, non-exported `type` / `interface` declarations, blank lines in a hunk that begins with pure `+`/`-` at a position where the prior code was removed. In a real monorepo this surfaces most often on file rewrites where new imports or types get inserted above the primary export.

## Suggested fixes

In rough order of scope:

1. **Broaden the walk-up.** Accept `TSInterfaceDeclaration` / `TSTypeAliasDeclaration` / plain `VariableDeclaration` at the top level, and if the node at the hunk's starting line isn't inside any declaration, scan forward within the hunk's line range instead of giving up. The hunk header already provides `new_start, new_len` — `LINE_RE` discards `new_len`; keeping it would let `find_node_at_line` try each line in the hunk until one matches.
2. **Fall back to "all exports from this file"** when per-line symbol lookup yields nothing but the file itself was meaningfully changed. A conservative overshoot that's strictly better than silently dropping consumers.
3. **Match symbols across old/new AST by name**, not by line-in-new-file, so a rewritten declaration with the same exported name still counts as a modification of that symbol. Largest change but removes the heuristic entirely.

(1) is the smallest fix and would cover the reproduction above.

## Environment

- Reproduces on `@front-ops/domino@1.2.1` and `@front-ops/domino@0.7.1`
- Rush workspace (the repro above uses `rush.json`)
- No `node_modules` present — bug reproduces on a bare clone

Happy to send a PR for direction (1) if maintainers agree with the approach.

### PR DESCRIPTION
**Pull request by nivnahmias**
Closes #62.

## Summary

`LINE_RE` in `src/git.rs` captured only the starting line of each diff hunk and dropped the count group (`,W`). With `--unified=0` (which `get_diff` always uses), a multi-line hunk like `@@ -3 +3,7 @@` contributed only line 3 to `changed_lines`, so `find_node_at_line` in `core.rs` only looked at line 3. Any exported symbol declared mid-hunk — on, say, line 8 — was invisible. With no traceable symbol, reference traversal was skipped and downstream consumers were silently dropped from the affected set.

This is direction (1) from the issue: capture the count group, expand each hunk's starting line to the full `start..start + count` range. When `,W` is absent git treats the hunk as a single line, so the count group stays optional and defaults to `1`.

## Change

`src/git.rs`:

```diff
-  LazyLock::new(|| Regex::new(r"@@ -.* \+(\d+)(?:,\d+)? @@").expect("line regex is valid"));
+  LazyLock::new(|| Regex::new(r"@@ -.* \+(\d+)(?:,(\d+))? @@").expect("line regex is valid"));
```

```rust
let mut changed_lines: Vec<usize> = line_regex
  .captures_iter(file_diff)
  .filter_map(|caps| {
    let start: usize = caps.get(1)?.as_str().parse().ok()?;
    let count: usize = caps
      .get(2)
      .and_then(|m| m.as_str().parse().ok())
      .unwrap_or(1);
    Some(start..start + count)
  })
  .flatten()
  .collect();
```

## Tests

Added three new unit tests in `src/git.rs`:

- **`test_parse_diff_multi_line_hunk_covers_full_range`** — mirrors the issue's reproduction. Hunk `@@ -3 +3,7 @@` must produce `[3, 4, 5, 6, 7, 8, 9]`. This is the regression test.
- **`test_parse_diff_shorthand_count_defaults_to_one`** — pins the fallback for hunks emitted without `,W` (e.g. `@@ -1 +1 @@`).
- **`test_parse_diff_pure_deletion_hunk_contributes_zero`** — uses a diff with a pure-deletion hunk (`+Z,0`) paired with a real addition hunk, so the assertion targets the "deletion contributes nothing" behavior rather than the file-skip branch.

Updated two existing tests whose expected output changes because their hunks now contribute every line rather than just the first:

- `test_parse_diff` — the second file's hunk `@@ -102,0 +103,2 @@` now yields `[103, 104]` (was `[103]`).
- `test_parse_diff_renamed_file_with_changes` — hunks `@@ -5,1 +5,1 @@` and `@@ -20,0 +20,3 @@` now yield `[5, 20, 21, 22]` (was `[5, 20]`).

All 13 `git::tests::*` pass (`cargo test --lib`), along with the full 184-test `--lib` suite. `cargo fmt -- --check` passes. `cargo clippy` on `src/git.rs` emits no warnings.

## Caller impact

Reviewed every use of `ChangedFile.changed_lines`:

- `core.rs:147-161` — for each line, looks up a symbol via `find_node_at_line`, then deduplicates via `unique_symbols: FxHashSet<&String>`. Extra lines inside the same exported declaration collapse into one trace; extra lines outside any declaration contribute an empty `Vec<String>` and do nothing. No behavioural change except that the bug is fixed.
- `core.rs:269-289` — one `AffectCause::DirectChange { line }` entry per line for asset causes. The report will now list more cause entries per affected package on multi-line hunks, which is a correctness improvement (previously under-reported).
- `lockfile.rs` — only reads `file_path`; never reads `changed_lines` outside test fixtures.

No changes to `ChangedFile`, no new public API.

## Out of scope

Directions (2) and (3) from the issue (fallback to all exports; old/new AST matching) are deferred as future improvements per the maintainer's triage.

## Manual validation

Against the minimal fixture from the issue (`/tmp/domino-repro`, a two-package Rush workspace where `package-b` imports a symbol from `package-a`'s `foo.ts`):

| Branch | Before | After |
|---|---|---|
| `simple-edit` (1-char body change) | `[package-a, package-b]` | `[package-a, package-b]` |
| `rewrite` (interface inserted before export) | `[package-a]` ❌ | `[package-a, package-b]` ✅ |

Both branches now correctly mark `package-b` as affected.

## Summary by CodeRabbit

* **Bug Fixes**
  * Git diff parsing now correctly recognizes optional hunk lengths and records the full inclusive new-side line ranges for multi-line hunks, and preserves files that are deletion-only with an empty changed-line list.

* **Tests**
  * Added and updated regression tests for multi-line hunks, shorthand hunk counts, pure-deletion hunks, and full-range line coverage.

### CODE REVIEW

File: src/git.rs [hunk 1]
```diff
@@ -187,11 +187,22 @@ fn parse_diff(diff: &str) -> Result<Vec<ChangedFile>> {
...
+        .filter_map(|caps| {
+          let start: usize = caps.get(1)?.as_str().parse().ok()?;
+          let count: usize = caps
+            .get(2)
+            .and_then(|m| m.as_str().parse().ok())
+            .unwrap_or(1);
+          Some(start..start + count)
+        })
+        .flatten()
         .collect();
```
Comment (EladBezalel) [inline src/git.rs:216]: Nit: the `filter_map` chain silently swallows parse errors via `.ok()?`. Since `\d+` makes non-numeric captures impossible this is low risk, but it's inconsistent with the `warn!` usage elsewhere in this function. Consider:

```rust
let start: usize = caps.get(1)?.as_str().parse().ok()?;
// could be:
let start: usize = match caps.get(1)?.as_str().parse() {
    Ok(v) => v,
    Err(_) => { warn!("Failed to parse hunk start line"); return None; }
};
```

File: src/git.rs [hunk 2]
```diff
@@ -445,4 +456,75 @@ copy to src/copied.ts
...
+--- a/packages/package-a/src/foo.ts
++++ b/packages/package-a/src/foo.ts
+@@ -3 +3,7 @@ import { helper } from './helper.js';
+-export const foo = (x: number): number => helper(x) + 1;
++interface FooOptions {
++  offset: number;
++  multiplier: number;
++}
++
++export const foo = (x: number, options: FooOptions = { offset: 1, multiplier: 3 }): number =>
```
Comment (EladBezalel) [inline src/git.rs:496]: The regression test uses `@@ -3 +3,7 @@` (asymmetric, no old-side count) — the exact format from issue #62. Consider adding a case with the common symmetric format `@@ -3,7 +3,7 @@` to confirm the greedy `.*` handles both correctly. A future regex change could break the common case without this coverage.

**Review by EladBezalel — COMMENTED** [review]
Clean, minimal fix that directly addresses the root cause from #62. The regex and range expansion are correct. A few suggestions below, nothing blocking.

### Performance note

`find_node_at_line` is now called once per expanded line instead of once per hunk. A 500-line rewrite → 500 AST traversals instead of 1. The `FxHashSet` dedup at `core.rs:200` prevents redundant *reference traversal* but not the redundant *AST lookups*. In practice most hunks are small and AST traversal is fast, so this is unlikely to be measurable for typical diffs. A batch `find_nodes_in_range(start, end)` API would be a nice follow-up optimization but shouldn't block this correctness fix.

### Pre-existing: pure-deletion files silently dropped

When every hunk in a file is a deletion (`+Z,0`), `changed_lines` is empty and `parse_diff` returns `None` — the file is excluded. The deletion test in this PR sidesteps it by pairing with an addition hunk. Not introduced by this PR, but worth a separate issue.

**Comment by nivnahmias** [comment]
Thanks for the review!

Quick clarification on the pure-deletion finding — it's actually a regression my PR introduced, not pre-existing. In the old regex `@@ -.* \+(\d+)(?:,\d+)? @@`, the count group was non-capturing, so `@@ -5,3 +5,0 @@` still captured `5` as the start and the file was kept (with `changed_lines = [5]`). After my change, `count = 0` produced an empty range and the file got dropped by `parse_diff`. Since it's part of the same commit's blast radius, I addressed it inline in `598ebd7` rather than leaving it as a separate follow-up:

- `parse_diff` now tracks whether any hunk headers were seen (even `+Z,0` ones) and keeps the file with empty `changed_lines` in that case, so its owning package is still marked via `core.rs`.
- Added `test_parse_diff_deletion_only_file_kept_with_empty_lines` to lock the behaviour in.

Also obfuscated the external repo URL in the regression test comment per the other bot review.

Re: the perf note — agreed, a `find_nodes_in_range` batch API sounds like the right long-term shape.

**Comment by EladBezalel** [comment]
Good catch on the deletion regression — you're right, the old regex captured `5` from `@@ -5,3 +5,0 @@` as a start line (count was non-capturing), so the file was kept. The `has_hunks` fix in `598ebd7` is clean.

The updated diff looks good. Two minor items still open from my inline comments — both are nits, not blocking:

1. **Silent parse error** (line 203): `.ok()?` still swallows parse failures silently. Low risk since `\d+` prevents non-numeric captures, but a `warn!` would be consistent with the rest of the function.

2. **Symmetric hunk test**: No test covers `@@ -3,7 +3,7 @@` (the common format where the old-side also has a count). The greedy `.*` handles it, but a test would guard against future regex changes.

Neither is blocking — LGTM on the fix.

**Review by EladBezalel — APPROVED** [review]
Correctness fix for a real bug, minimal scope, solid test coverage including the deletion-only regression catch. LGTM.
